### ISSUE TITLE
FE ranking doesn't follow API content values.

### ISSUE THREAD

**Issue by nastasi-oq** [GFDRR/open-risk-data-dashboard#129]
In https://dev.riskopendata.org/countries.html countries with the same score must have the same ranking (as returned by the API) but not in the page.

**Comment by CIMAManuel** [comment]
Question: countries without rank what can i show? Zero (0) value?

**Comment by pzwsk** [comment]
Countries with no datasets submitted (without rank) should rank last, with adequate rank value. So in order to respond I need to know the ranking system used by the API?  Is there a gap in ranking after same scores or not?

It is 1224 ranking, 1334 ranking or 1223 ranking ?
See for detail https://en.wikipedia.org/wiki/Ranking

If there is a gap, then rank value = total number of countries
If there is no gap, then rank value = last rank + 1

**Comment by nastasi-oq** [comment]
@pzwsk currently we haven't  gap
I fixed rank for detailed view of countries without datasets using the logic:
`rank =  last_rank (if last score == 0.0)`
`rank  = last_rank + 1 (if last score > 0.0)`
Here the code: https://github.com/GFDRR/open-risk-data-dashboard/pull/130
For @CIMAManuel : it is already on `dev`

**Comment by pzwsk** [comment]
Ok, this is fine with me.

@CIMAManuel, just make sure to apply this for countries.html

Thanks
