### ISSUE TITLE
Add an interactive map above the table of countries.

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/open-risk-data-dashboard#279]
We can talk about the various visualization options of the map. It would be similar to https://opendri.org/project/ but with clickable country polygons instead of points, and several other options for visualizing how complete / how open each country's index is.

**Comment by pzwsk** [comment]
To be discussed in relation to #264

Some comments:

* I would avoid table and map on same page - too much info and interaction. We can use different tabs but need to check performance issue. Otherwise, let's have a dedicated page;

* Need to get shapefile of national boundaries (ask Stu);

* A very nice to have, but I would not put it as a priority, compare to new scoring and filter feature for table;

**Comment by vdeparday** [comment]
As I argued at the beginning of the project, I don't think a map is the
right way to visualize this data. I am not sure what it brings ? Maybe the
one thing related to geography and distance on this, would be if
neighbouring country are influencing each other. But I think a filter per
region on the table  would likely be more effective way of communicating
this.

**Comment by pzwsk** [comment]
Ok thanks, let's put that issue aside for now.

Also, please have a look to new Explore countries page including filter by country regions https://dev.riskopendata.org/countries.html

**Comment by gracedoherty** [comment]
Hi - actually I wrote this issue during a rapid brainstorming for a front end sprint with Thomas. I should have closed it during that session. Will do so now. 

Agreed on focusing first on the filtering and scoring. Any other visualization options can be considered after we've seen how all of that shapes up.
