### ISSUE TITLE
Dataset details page: Alternative datasets

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#341]
Show alternative World and Country datasets (dataset submitted for similar key dataset)

![image](https://user-images.githubusercontent.com/2378439/49458980-42cfec80-f7ee-11e8-8107-a0d67a369e8b.png)

fix #340

**Comment by pzwsk** [comment]
Hi @gracedoherty, 

yes this is the idea but only showing alternative datasets at world level or similar country level, I removed country group from the list.

I think we need to find right balance between showing enough for alternative datasets and avoiding page to show too much info. 

Also, showing dataset at the bottom of the page was not a good choice.

Maybe we can find a way to show both dataset title and open data criteria OR dataset title and open data status (open data, restricted, closed, unknown). This might be an improvement of current issue.

See current suggestion in screenshot above.

**Comment by gracedoherty** [comment]
As long as the Country and Explore Datasets pages show the open/restricted/closed/unknown status of all the relevant datasets side-by-side, I don't think it's necessary to add that status next to the alternative datasets on this page.

Agreed on not including the full alternative datasets listing on this page, just wanted to clarify.

Regarding the ordering of Country and World lists: whichever of the two is (typically) more useful should be listed first. My inclination is to have Country datasets above World datasets (opposite of what you're showing here), because I assume the Country level alternative is still better overall than the World one (i.e. higher resolution even if less open, more attributes, etc.). But maybe you disagree, based on the datasets you've been seeing submitted.

Otherwise I think what you've designed here is good.

**Comment by oncletom** [comment]
@pzwsk small question: how is that supposed to work when the dataset is a World Level dataset?
