### ISSUE TITLE
Explore countries: truncate dataset reference if larger than 2 lines

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#371]
- Truncate dataset reference (title, publisher, date) to 2 lines max with [...] at the end if longer
- Ensure same height size for all rows

See issue below
![image](https://user-images.githubusercontent.com/2378439/50157933-019e0900-02d3-11e9-945d-d791850243d3.png)

**Comment by pzwsk** [comment]
Hi @CIMAManuel could you have a look at this one?

Thanks!

**Comment by pzwsk** [comment]
As per @oncletom in #377, this is only working on Chrome.

I putting back issue to In Progress.

**Comment by dedandy** [comment]
Are you like this?! ... It's not easy because the block of _subtitle_datasetlist_ is composed by 3 object (title + institution + modify_time) and every object may be short or longer and all may exceed 2 lines. Sure I'm try to fix just use visual html & css capabilities... Another way will be to use JS to count words or charachters...
Well this is the fix now


Firefox preview:
![opendri_index_-_datasets_list_-_2018-12-21_10 18 55 png_-_2018-12-21_10 19 28](https://user-images.githubusercontent.com/2742862/50334917-07316400-050a-11e9-80b8-3659b3e195cb.png)

chrome preview:
![5084874806132736](https://user-images.githubusercontent.com/2742862/50335097-8f176e00-050a-11e9-9439-80f73def9405.png)

**Comment by pzwsk** [comment]
I understand.

Is there no possibility to treat it as one object?

Also, in examples above, the three dots are always there. That should not
be the case.

**Comment by CIMAManuel** [comment]
We pushed in the branch named "#371_trunk_over2lines" the last version of this issue.
There are some problems with Firefox yet, but we can't do better.
If you have any ideas (@pzwsk , @oncletom ).

**Comment by pzwsk** [comment]
Hi @CIMAManuel @dedandy  still need to merge your fix in dev, right?

**Comment by oncletom** [comment]
I'm happy to have a look at it.
