### ISSUE TITLE
If data is not openly licensed, shouldn't be here

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/open-risk-data-dashboard#388]
I would suggest that if a dataset is not openly licensed, it should not even be considered for inclusion in this website - therefore we could remove the criterion _"Is the data openly licensed?"_ and redistribute the 30% weight to the other criteria. What do you think?

Also, license is written with both the American (_license_) and the British (_licence_) spelling in the documentation page - we should pick one ;)

**Comment by pzwsk** [comment]
Thanks, will check spelling for license versus licence > #390 

I disagree with suggestion to remove the open license criteria as the aim of the website is to evaluate whether a dataset is open or not, both technically and legally.

Currently, we are using the criteria and score from the former Open Knowledge Index. See https://en.wikipedia.org/wiki/Open_Data_Indices#Scoring_standard

However, I do agree that there is room for improvement.

For instance current criteria do not take into account:
* Open standard versus proprietary file format
* When a user has to register and login to download the dataset

Best

**Comment by pzwsk** [comment]
Thanks Thomas, 

I would sure agree data is better than no data ;) 

However, the whole concept of open data is to help people go beyond their community and share data with anyone and not only think about the risk and legal framework within their community.

It is surely something we need to explain better and again and again through the Index but also in our communication, that on a global scale, licensing (legal clarity) does matter.

Actually, would be interesting to capture some good cases to highlight licensing issue in DRM. Some I have in mind:

* Impossibility for HOT community to re-use copyrighted material, even in time of crisis, because of legal uncertainty / no compatible license;
* Release of some Digital Globle imageries in open license during disasters;
* Etc.

**Comment by oncletom** [comment]
Agreed. To me the opportunity is to enact a change to license the data, by making the absence of license visible on the Index. As someone said to me yesterday, they don't have an open data portal in their country, so the Index is a great way to find/contribute resources.
